Introducing parsing an errors from a server response
lumeohq/api-client pull request #13
Opened 2021-10-27 10:54 UTC by silvestrpredko

### Briefly 
- Added parsing errors from server response
- Adding a new error is simplified for consistency between client and server, **(please take a look at macro)**
- Added some tests to check if macro does his job
 
Would be awesome to add integration tests, and emulate some calls from the server. (But it's not in the scope of this task)

2021-11-01 12:16 UTC, jplatte requested changes
I continue to disagree with copying the definitions of the error codes we have in API server here. Lumeod will only ever need to handle a tiny subset of those errors. In all other cases, just capturing the `code` and `message` will give all the context necessary. I highly suggest to only keep what's currently named `ApiServerResponse` (probably as `ApiError`) with a `message` field (for printing the error) and removing the enum and the macro that generates it.

After seeing the changes I agree that it makes sense to use the same error type for the lower-level methods (defined in `lib.rs`) as for everything else, but then we don't need separate `HttpError` and `Error` types. As-is, the `Error` type doesn't always contain information on which route the error happened under, which will make errors harder to diagnose. I think we should rename the existing `HttpError` to just `Error` and add the new error variants to it.

2021-11-01 12:16 UTC, jplatte commented on src/error.rs
> +            _ => write!(f, "{:?}", self),
Please don't use `Debug` formatting in a `Display` implementation. The other match arms should look more like the first one or use `write!` with some extra context like the `Display` implementation for `HttpError`.

2021-11-03 15:22 UTC, silvestrpredko commented
> I continue to disagree with copying the definitions of the error codes we have in API server here. Lumeod will only ever need to handle a tiny subset of those errors. In all other cases, just capturing the `code` and `message` will give all the context necessary. I highly suggest to only keep what's currently named `ApiServerResponse` (probably as `ApiError`) with a `message` field (for printing the error) and removing the enum and the macro that generates it.
> 
> After seeing the changes I agree that it makes sense to use the same error type for the lower-level methods (defined in `lib.rs`) as for everything else, but then we don't need separate `HttpError` and `Error` types. As-is, the `Error` type doesn't always contain information on which route the error happened under, which will make errors harder to diagnose. I think we should rename the existing `HttpError` to just `Error` and add the new error variants to it.

@DmitrySamoylov Could you please also participate in this discussion. I suggested keeping macro with all errors description.

2021-11-03 15:36 UTC, DmitrySamoylov commented
Sure, I like discussions :smiley: 

> removing the enum and the macro that generates it.

I think it can be useful to match on enum instead of `code` string. It is also easy to maintain a compatible set of errors by just copying the whole enum from API server. TBH I'm not sure which errors lumeod will need soon but if it Is easy to have them all, why not?

2021-11-03 15:43 UTC, jplatte commented
> I think it can be useful to match on `enum` instead of code string.

What about matching the string against a named constant?

> why not?

It's more code (=> more potential for programmer errors) that also has to be synchronized manually with the corresponding api-server code. Also with the current code in this PR, a variant that exists on the server but not in the client (for example because the server has had an update but no new lumeod release has happened yet), we would get an ugly deserialization error instead of an `ApiError { code: "new-error-code", message: "Something went wrong" }`.

2021-11-03 15:57 UTC, DmitrySamoylov commented
Ah, then `Unknown(String)` variant that @silvestrpredko added initially (https://github.com/lumeohq/api-client/pull/13#discussion_r737402994), now makes sense. It would catch all deserialization errors. When matching, it would be the same as named constants: all unrecognized stuff will go under `_ => ...`.

> It's more code (=> more potential for programmer errors)

Do you mean code of macro or enum? For macro this is true, that syntax requires some experience.

2021-11-03 16:22 UTC, silvestrpredko commented
I am not insisting on macro, but I don`t like a string matching approach. It's also error-prone. It would be great to have the same errors in the client and server, but it's not possible for now.

2021-11-03 16:35 UTC, jplatte commented
> > It's more code (=> more potential for programmer errors)
> 
> Do you mean code of macro or enum? For macro this is true, that syntax requires some experience.

I was mainly thinking of the additional deserialization code to turn the `ApiServerResponse` into `ApiError`. It applies to the macro generating that code too though.

@DmitrySamoylov do you agree it's reasonable to only include errors relevant to lumeod (for now) to keep the work needed to synchronize the errors between api-server and api-client to the minimum required?

2021-11-03 16:40 UTC, DmitrySamoylov commented
> only include errors relevant to lumeod (for now)

If we don't just copy-paste errors from api-server or generate from api-docs then yes, not much sense in maintaining the full set of errors.

2021-11-03 18:21 UTC, silvestrpredko commented
So as I understood we agree to move from macro to parsing relevant to api-client errors?

2021-11-03 18:23 UTC, silvestrpredko commented
@jplatte Why we don't have the same shared crate for errors between client and server?

2021-11-03 18:25 UTC, jplatte commented
I would prefer not to add more git dependencies that we have to update regularily, because that is also extra busywork. Also the server doesn't need the enum that the client needs.

2021-11-03 18:28 UTC, silvestrpredko commented
> I would prefer not to add more git dependencies that we have to update regularily, because that is also extra busywork. Also the server doesn't need the enum that the client needs.

I am just curious, because we have the same tool on both sides, but still need to parse it by our own hands :(

2021-11-03 18:31 UTC, jplatte commented
Yeah it's our own software on both sides, but there is no guarantee of the two always being in sync version-wise so it would be problematic to blindly assume that the client knows all the (error) cases.

2021-11-03 18:43 UTC, silvestrpredko commented
> Yeah it's our own software on both sides, but there is no guarantee of the two always being in sync version-wise so it would be problematic to blindly assume that the client knows all the (error) cases.

I suggest that the client doesn't need to know all errors that are happening on the server-side, but having the single crate for errors automatically removes the requirement for the client to parse errors from the server. I think it's a good point. And regarding updating dependencies, if it's our software, why we are not using branches instead of commits? With branches, we always will have the latest release versions of our dependencies.

Please write your thoughts, maybe I miss something.

2021-11-04 10:45 UTC, jplatte commented on src/apps.rs
> +use crate::Error;
A common pattern when there is an error type in a crate that's returned from a lot of functions is adding

```rust
type Result<T, E = Error> = std::result::Result<T, E>;
```

at the crate root and importing that. Then, the return type of the functions can be simplified:

```rust
/* from */ Result<Application, Error>
/* to   */ Result<Application>
```

2021-11-04 10:45 UTC, jplatte commented on src/error.rs
> +    GatewayDeleted,
The provisioning code uses the `InvalidCredentials` error, can you add that one?

2021-11-04 10:45 UTC, jplatte commented on src/error.rs
> +    code: String,
Please also include the `message` field so we can log it in error messages.

2021-11-04 10:45 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
Can you please add a `ApiError::Other` variant holding `ApiServerResponse` and return that here? Not for matching on it but to have better `Debug` / `Display` implementation.

2021-11-04 10:45 UTC, jplatte commented on src/error.rs
> +            ApiError::GatewayDeleted => write!(f, "ApiError : GatewayDeleted"),
`Display` is for human-readable messages, can we use the full error message here?

```suggestion
            ApiError::GatewayDeleted => write!(f, "The gateway this access token belonged to has been deleted"),
```

2021-11-04 10:45 UTC, jplatte commented on src/error.rs
> +    fn http_context(self, method: Method, path: &str) -> Result<T, Error>;
Since the dependency on `anyhow` has been removed and the error type is no longer called `HttpError`, I would suggest renaming this method to just `context`.

2021-11-04 10:45 UTC, jplatte commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
What do you think about having one variant containing a struct with the details + inner variant here? Something like

```suggestion
    Request(RequestError),
```

with

```rust
struct RequestError {
    pub method: Method,
    pub path: String,
    pub kind: RequestErrorKind,
}

enum RequestErrorKind {
    Url(url::ParseError,
    Query(serde_urlencoded::ser::Error),
    Reqwest(reqwest::Error),
    Api(ApiError),
}
```

2021-11-04 11:40 UTC, silvestrpredko commented on src/error.rs
> +    code: String,
I am not using the message, so don't see a necessity to add this field.

2021-11-04 11:48 UTC, jplatte commented on src/error.rs
> +    code: String,
If we add `ApiError::Other`, then `message` is what we should print from the `Display` implementation.

2021-11-04 11:48 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
I think that deserialization Error is enough to see what is goes wrong there. Do you think that output for this deserialization error will be awful?

2021-11-04 11:50 UTC, silvestrpredko commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
I think that is better approach, I will implement it

2021-11-04 11:53 UTC, silvestrpredko commented on src/error.rs
> +    fn http_context(self, method: Method, path: &str) -> Result<T, Error>;
Personally, I like more http_context, let's vote for this. @DmitrySamoylov

2021-11-04 11:55 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
I think that conceptually it doesn't make sense to report a deserialization error here. An api server response with an unknown code is still a valid error returned by the API (`ApiError`).

We can add `#[doc(hidden)]` to the `Other` variant so that autocompletion will never suggest using it (though actually making it private is unfortunately not possible).

2021-11-04 12:05 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
I disagree with this, it's a deserialization problem. I will explain my point. We have an enum with variants and if I have a response that I am not expecting it's a deserialization error because we know what server could send and predefined these errors on the client side. If I receive something that is unfamiliar for the client I will crash during serealization. It makes sense to add Unknown Error if I know for now all errors but for some reason doesn't want to define them in client, and move these errors to Unknown variant.

2021-11-04 12:07 UTC, silvestrpredko commented on src/error.rs
> +    code: String,
We could add a message field and it automatically will be printed with deserialization Error

2021-11-04 12:10 UTC, jplatte commented on src/error.rs
> +    fn http_context(self, method: Method, path: &str) -> Result<T, Error>;
Since it only adds http-specific data, I'm also fine keeping it as-is.

2021-11-04 12:16 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
If we keep it this way, the error message in logs will be very noisy compared to what we would have if we just stored the `ApiServerResponse` and printed its message:

```
Some higher-level context: GET request to /v1/apps/UUID/something failed: Couldn't deserialize a: ApiServerResponse { code: "some-error-code", message: "Human-readable error description from server" }
```

as opposed to:

```
Some higher-level context: GET request to /v1/apps/UUID/something failed: Human-readable error description from server
```

2021-11-04 13:51 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
I suggest that:
`GET request to /v1/apps/UUID/something failed: Human-readable error description from server` 
will not be any better than just a debug. Because you still need to write the wrong code of error and message.
It could look similar to this: Server response error couldn't be deserialized because code `code` doesn't match any presented in the enum and message is ...

I suggest that printing a debug from ApiServerResponse seems less verbose.

2021-11-04 14:32 UTC, silvestrpredko commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
I remember why I don't do it in that way.
In `lib.rs` we have two functions.
``` Rust   
 fn application_id(&self) -> Result<Uuid, Error> {
    self.application_id.ok_or(Error::ApplicationIdMissing)
 }

 fn gateway_id(&self) -> Result<Uuid, Error> {
     self.gateway_id.ok_or(Error::GatewayIdMissing)
 }
```
If we will have a RequestError then I need to pass as parameters for these functions `Method` and `path` but these args don't have any relations with application_id and gateway_id. Also making the method and path  as
 Option doesn't seem very convenient for using.

2021-11-04 14:40 UTC, jplatte commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
I think you're misunderstanding. I was suggesting that `Error` would continue to be an enum, with variants `Request(RequestError)`, `ApplicationIdMissing` and `GatewayIdMissing`.

2021-11-04 15:00 UTC, silvestrpredko commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
I just tried to parse the error and it seems not very convenient to get an GatewayDeleted
```Rust
if let Error::Request(RequestError { kind , .. }) = er {
      if let RequestErrorKind::Api(ApiError::GatewayDeleted) = kind {
          
      }
}
```
```Rust
if let Error::Api(ApiError::GatewayDeleted, details) = err {
}
```

And if additional details are needed we easily get it from error or could skip it.

2021-11-04 15:58 UTC, jplatte commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
You can collapse the two `if let`s in the first example:

```rust
if let Error::Request(RequestError {
    kind: RequestErrorKind::Api(ApiError::GatewayDeleted),
    ..
}) = err
{
}
```

It's longer but doesn't introduce extra nesting.

I don't insist on changing it though.

2021-11-04 15:59 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
> you still need to write the wrong code of error and message

Can you explain what you mean by this? In what way can a code be *wrong*?

2021-11-04 16:08 UTC, silvestrpredko commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
Still, it seems more complicated than it needed. I don't think that method and path will be used a lot in error parsing on lumeod side.

2021-11-04 16:09 UTC, DmitrySamoylov commented on src/error.rs
> +    fn http_context(self, method: Method, path: &str) -> Result<T, Error>;
`http_context` is fine to me.

2021-11-04 16:14 UTC, DmitrySamoylov commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
Alternatively, you can make `path` and `method` optional.

2021-11-04 16:17 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
When we met an error code that doesn't define on the client side. For example account-disable. And in this case, we need to move `ApiServerResponse` into `deserialization::Error` or `Other` (`Unknown`) variant.
And I think that in display implementation we need to describe what happens. So I suggest that we still need to write the `code` and `message` that we received with `ApiServerResponse`. And this doesn't have a difference from a debug print.

2021-11-04 16:19 UTC, silvestrpredko commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
Yeah, I could but I don't see a problem with the current solution. Could you please write the pros and cons for both approaches?

2021-11-04 16:26 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
> And I think that in display implementation we need to describe what happens. So I suggest that we still need to write the `code` and `message` that we received with `ApiServerResponse`.

I disagree. When we get an error from the server, there is no need to distinguish between errors known to the client or unknown to the client in logs / when displaying the error to a user somewhere. There is also no need to include the error code since the message is unique on its own. The code is for matching against in code, not for display purposes.

2021-11-04 16:31 UTC, jplatte commented on src/error.rs
> +    ErrorDeserialization(reqwest::Error, ErrorDetails),
I think I was just overreacting to the use of a tuple enum variant with more than one field, which is often a bad idea, especially when types like `String` are used for the fields (which don't make it clear what the field represents).

The code inside `error.rs` might become a little bit clearer with the nested approach and it would be easier to access the path or method, but that's less important than matching on it so I agree that not changing this is better.

2021-11-04 16:34 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
But for the user is easier to check the code and understand what enum variant is missing, because code isn't some hex value, it's an enum variant in the kebab case.

Which log is easier to understand what enum variant is missing?
`Wrong email or password`
or 
`ApiServerResponse { code: `invalid-credentials` ...}`

2021-11-04 16:59 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
> Which log is easier to understand what enum variant is missing?

I see where you are coming from. However, I don't think that receiving an unknown error code implies that we have to add an enum variant.

An unknown error code could be coming from

* faulty code in the API server; for example added the wrong auth middleware for a new route, resulting in `not-a-user`
* faulty code in api-client; for example mistyped a field name, resulting in `invalid-body-arguments`
* or a number of other things; we might add a payload to the service unavailable error that happens when there is a problem connecting to the database

In all those cases, the right fix isn't to recognize this error within lumeod but to fix the underlying issue of the error.

2021-11-04 17:24 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
Exactly!
> In all those cases, the right fix isn't to recognize this error within lumeod but to fix the underlying issue of the error.

I suggest that it is better to show all the information that comes from lumeod(In this case) for faster troubleshooting. Let's imagine, a customer went to us and shows error logs. With which logs you will figure out faster where we have an issue?

```GET request to /v1/apps/UUID/something failed: Couldn't deserialize a: ApiServerResponse { code: "invalid-credentials", message: "Wrong email or password" }```

or with

```
GET request to /v1/apps/UUID/something failed: Wrong email or password
```

2021-11-04 18:08 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
> Let's imagine, a customer went to us and shows error logs.

I think if a customer sees the logs, the shorter message is far better because it provides all the necessary information while not being overwhelming. They might be able to do something about the error themselves.

> With which logs you will figure out faster where we have an issue?

I don't think it would make a difference.

2021-11-04 18:32 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
> I don't think it would make a difference.

I don't agree with that.

Let's vote for the solution. @DmitrySamoylov could you please participate, and help decide the way how it should be implemented?

2021-11-05 09:50 UTC, DmitrySamoylov commented on src/error.rs
> +const GATAWAY_DELETED: &str = "gateway-deleted";
```suggestion
const GATEWAY_DELETED: &str = "gateway-deleted";
```

2021-11-05 10:33 UTC, DmitrySamoylov commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
I think @jplatte convinced me that `Other` is better than deserialization error. If an error code is unrecognized, it is still a valid `ApiError`. After all, any unhandled error will go to logs. The question is whether we should log `Error::Api(ApiError)` or `Error::ErrorDeserialization`. I think the first one is better because it has all the needed properties, like `code`, `message`, etc. So, we recognize that it is `ApiError`, it is just the code that is unknown yet. But even if the code is not still present in Rust representation, it still can be printed.

So I vote for `GET request to /v1/apps/UUID/something failed: Other { code: "invalid-credentials", message: "Wrong email or password" }`.

2021-11-05 10:58 UTC, DmitrySamoylov commented on src/error.rs
>  #[derive(Debug)]
@silvestrpredko @jplatte, I have an idea. We can use `strum` to make deserialization less error-prone.

```suggestion
use strum::AsRefStr;

#[derive(AsRefStr, Debug)]
#[strum(serialize_all = "kebab-case")]
```

And then inside `impl<'de> Deserialize<'de> for ApiError` we can write:

```rust
match resp.code.to_kebab_case().as_str() {
    e if e == ApiError::GatewayDeleted.as_ref() => Ok(ApiError::GatewayDeleted),
    e if e == ApiError::InvalidCredentials.as_ref() => Ok(ApiError::InvalidCredentials),
    ...
```

This way we can remove string constants at all.

Isn't it awesome? :smile:

2021-11-05 11:20 UTC, jplatte commented on src/error.rs
> +        match resp.code.to_kebab_case().as_str() {
`to_kebab_case` is not needed because error codes are always in kebab-case.

2021-11-05 11:20 UTC, jplatte commented on src/error.rs
>  #[derive(Debug)]
If we're going to use `strum` we can also use `strum::EnumString` to generate half the `Deserialize` impl, using `#[strum(disabled)]` on the `Other` variant and omitting these constants.

2021-11-05 11:24 UTC, jplatte commented on src/error.rs
>  #[derive(Debug)]
That is:

```rust
let resp = ApiServerResponse::deserialize(deserializer)?;
match resp.code.parse() {
    Ok(e) => e,
    Err(_) => ApiError::Other { code: resp.code, message: resp.message },
}

2021-11-05 11:28 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
So as a result will be implemented Display with such content:
`write!(f, "{:?}", other)?
@DmitrySamoylov

2021-11-05 11:29 UTC, DmitrySamoylov commented on src/error.rs
>  #[derive(Debug)]
Yeah, even better.

> If we're going to use strum

We already use it: https://github.com/lumeohq/api-client/blob/7f25d2ece4acd702abd38bdae516207f18ccf87d/Cargo.toml#L19

2021-11-05 11:32 UTC, jplatte commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
I still think that we shouldn't use `Debug` formatting inside a `Display` implementation. If you both agree that we should print the code, how about

```rust
write!(f, "{} (`{}`)", code, message)
```

so that we have

```
GET request to /v1/apps/UUID/something failed: Wrong email or password (`invalid-credentials`)
```

2021-11-05 11:40 UTC, DmitrySamoylov commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
Ah, I confused `ApiError` with `ApiServerResponse` :facepalm: Have to re-read everything.

2021-11-05 11:41 UTC, DmitrySamoylov commented on src/error.rs
> +            ApiError::GatewayDeleted => write!(f, "ApiError : GatewayDeleted"),
Do we need `Display` at all if we have a human-readable `message` from the server?

2021-11-05 11:42 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
> GET request to /v1/apps/UUID/something failed: Wrong email or password (`invalid-credentials`)

I am ok with that.

2021-11-05 11:58 UTC, DmitrySamoylov commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
What if we have this:

```rust
#[derive(Debug)]
pub enum Error {
    Url(url::ParseError, ErrorDetails),
    Query(serde_urlencoded::ser::Error, ErrorDetails),
    Reqwest(reqwest::Error, ErrorDetails),
    Api(ApiError, ErrorDetails),
    ApplicationIdMissing,
    GatewayIdMissing,
}

#[derive(Debug)]
pub struct ApiError {
    code: ApiErrorCode,
    message: String,
}

#[derive(Debug)]
pub enum ApiErrorCode {
    GatewayDeleted,
    InvalidCredentials,
    Other(String),
}
```

And instead of `impl Display` user could print `message`.

2021-11-05 12:00 UTC, jplatte commented on src/error.rs
> +            ApiError::GatewayDeleted => write!(f, "ApiError : GatewayDeleted"),
Yes, we need it for the type to be able to implement `std::error::Error`. It will likely be used for logs.

2021-11-05 12:09 UTC, DmitrySamoylov commented
Since our error type is getting more or less complex, why don't we use `thiserror` instead of implementing conversions and `Display`'s manually?

2021-11-05 12:15 UTC, jplatte commented
> Since our error type is getting more or less complex, why don't we use `thiserror` instead of implementing conversions and `Display`'s manually?

I originally didn't use it because its automatic implementation of `Error::source` wouldn't work with the inner enum approach. Since we no longer have an outer struct and inner enum, we can now use `thiserror` and get the same generated code (as long as we put `#[source]` on the first field of the tuple variants).

2021-11-05 12:18 UTC, jplatte commented on src/lib.rs
> +pub type HttpResult<T> = Result<T, Error>;
Since the error type is no longer called `HttpError`, the corresponding result type should be renamed too:

```suggestion
pub type Result<T, E = Error> = std::result::Result<T, E>;
```

(with an extra `E` parameter that defaults to our `Error` type so it can still be used with a different error type)

2021-11-08 10:07 UTC, silvestrpredko commented on src/error.rs
> +            _ => Err(serde::de::Error::custom(format!("Couldn't deserialize a: {:?}", resp))),
Hmm then message should be a public field.

2021-11-10 15:08 UTC, silvestrpredko commented
Please review as it is, I don't want to rebase each commit from main. After review, I will squash all commits and rebase from main.

2021-11-10 15:24 UTC, jplatte reviewed
I still have a few comments, but nothing major.

2021-11-10 15:24 UTC, jplatte commented on Cargo.toml
> +heck = "0.3.3"
It doesn't seem like we actually use this anymore.

2021-11-10 15:24 UTC, jplatte commented on src/error.rs
> +pub enum ClientError {
Since this is the "main" error type of the crate (the one we return everywhere), I think it should be named just `Error`.

2021-11-10 15:24 UTC, jplatte commented on src/lib.rs
> +pub type HttpResult<T, E = ClientError> = std::result::Result<T, E>;
Same thing here, I think this type alias should be called just "Result" (as suggested before).

2021-11-10 15:42 UTC, silvestrpredko commented
> I still have a few comments, but nothing major.

I will squash and then fix comments don't want to spend time a lot of time on fixes

2021-11-10 15:46 UTC, jplatte commented on src/lib.rs
> +pub type HttpResult<T, E = ClientError> = std::result::Result<T, E>;
What do you mean by that? How is it easier to work with?

2021-11-10 16:06 UTC, silvestrpredko commented on src/lib.rs
> +pub type HttpResult<T, E = ClientError> = std::result::Result<T, E>;
It's just more convenient for work with, you type HttpResult and already know what kind of error it will have. As it's not critical I will leave it as it is.

2021-11-10 16:11 UTC, DmitrySamoylov commented on Cargo.toml
> +lumeo-commands = { git = "https://github.com/lumeohq/lumeo-types-rs", rev = "afcd6fc" }
Rebasing artifact :) `lumeo-commands` was removed in `main`.

2021-11-10 16:16 UTC, DmitrySamoylov commented on src/lib.rs
> +pub type HttpResult<T, E = ClientError> = std::result::Result<T, E>;
It is common to have `Result`/`Error` in public library API and in user code you can either import it under another name (`use api_client::Error as ClientError`) or use full path (`fn somefn() -> api_client::Result`). We do that for anyhow, for example: https://github.com/lumeohq/lumeod/blob/b521be41537af44e4e9d7fd193d07f4b5677a2c2/webrtcd/src/peer.rs#L217

2021-11-10 16:29 UTC, DmitrySamoylov approved these changes
Great work :+1:

2021-11-10 16:33 UTC, jplatte approved these changes

2021-11-10 17:27 UTC, merged